function angularRateTrue = GenerateTrueMotion(t)

    angularRateTrue = [ ...
        deg2rad(12) * sin(0.7 * t); ...
        deg2rad(8) * cos(0.5 * t); ...
        deg2rad(15) + deg2rad(4) * sin(0.3 * t)];

end
